---
- name: Install packages for SNMP
  apt: 
    name: 
      - snmpd
      - snmp
      - libsnmp-dev
    state: latest
    update_cache: true 

- name: Settings 'community string' and 'location' and 'contact' for SNMP 
  lineinfile:
    dest: "/etc/snmp/snmpd.conf"
    line: '{{ item }}'
  loop: 
    - rocommunity {{ rocommunity }}
    - syslocation {{ syslocation }}
    - syscontact {{ syscontact }}

- name: Stop snmpd 
  service: 
    name: snmpd
    state: stopped

- name: Create user for SNMP V3
  command: 
    cmd: net-snmp-create-v3-user -{{ method }} -A {{ authpass }} -a {{ md5_or_sha }} -X {{ privpass }} -x {{ aes_or_des }} {{ username }}
  notify:
    - Start and enable snmpd 